[install.security]
scanner = "@bun-security-scanner/osv"

[test]
coverage = true
coveragePathIgnorePatterns = ["dist/**", "example/**", "tests/**", "testSetup.ts"]
coverageThreshold = 0.9
preload = ["./testSetup.ts"]